apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eibcr9r2w-go 
  janus-idp.io/tekton: eibcr9r2w-go
  backstage.io/kubernetes-id: eibcr9r2w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eibcr9r2w-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml